use prabasededatos;

#INSERT INTO especies (nombre_especie) VALUES ('Canino'), ('Felino'), ('Ave'), ('Reptil'),('Roedor'),('Bovidos'),('Peces');

/*INSERT INTO razas ( id_especie, nombre_raza) VALUES
(7, 'Angel'),
(7, 'Betta'),
(7, 'Cebra'),
(7, 'Guppy'),
(7, 'Tetra neon'),
(7, 'Planty'),
(7, 'Molly negro'),
(7, 'Corydora paleatus'),
(7, 'Disco'),
(7, 'Ramirezi'),
(7, 'Otro');*/

/*INSERT INTO razas ( id_especie, nombre_raza) VALUES
(6, 'Otro'),
(6, 'Bovino'),
(6, 'Porcino'),
(6, 'Ovino'),
(6, 'Caprino'),
(6, 'Equino'),
(6, 'Camelido')
;*/

/*INSERT INTO razas ( id_especie, nombre_raza) VALUES
(5, 'Otro'),
(5, 'Ardilla'),
(5, 'Ardilla coreana'),
(5, 'Chinchilla'),
(5, 'Cobaya abisina'),
(5, 'Cobaya peruana'),
(5, 'Cobaya'),
(5, 'Conejo alaska'),
(5, 'Conejo arlequín'),
(5, 'Conejo azul de viena'),
(5, 'Conejo belier enano'),
(5, 'Conejo cabeza de león'),
(5, 'Conejo de Angora'),
(5, 'Conejo enano'),
(5, 'Conejo holandés'),
(5, 'Conejo holandés enano'),
(5, 'Conejo polaco'),
(5, 'Conejo rex'),
(5, 'Conejo tan'),
(5, 'Conejo teddy'),
(5, 'Cricetomyinae'),
(5, 'Degú'),
(5, 'Erizo'),
(5, 'Erizo africano'),
(5, 'Hámster'),
(5, 'Hámster chino (Cricetulus griseus)'),
(5, 'Hámster común'),
(5, 'Hámster dorado'),
(5, 'Hámster enano'),
(5, 'Hámster ruso'),
(5, 'Hámster teddy'),
(5, 'Hurones'),
(5, 'Jerbo de Mongolia'),
(5, 'Jerbo persa'),
(5, 'Lemmings'),
(5, 'Liebre'),
(5, 'Rata'),
(5, 'Ratón');*/

/*INSERT INTO razas ( id_especie, nombre_raza) VALUES
(4, 'Otro'),
(4, 'Gecko'),
(4, 'Camaleon'),
(4, 'Tortuga de agua'),
(4, 'Iguana'),
(4, 'Serpiente'),
(4, 'Pogona')
;*/

/*INSERT INTO razas ( id_especie, nombre_raza) VALUES
(3, 'Otro'),
(3, 'Guacamayo'),
(3, 'Cacatua'),
(3, 'Perico'),
(3, 'Gallina'),
(3, 'Pato pekin'),
(3, 'Pato criollo'),
(3, 'Pato mulard'),
(3, 'Pavo'),
(3, 'Gansos'),
(3, 'Codornice'),
(3, 'Pintadas (Gallinas de Guinea)'),
(3, 'Palomas');*/

/*INSERT INTO razas ( id_especie, nombre_raza) VALUES
(2, 'Mestizo'),
(2, 'American Bobtail'),
(2, 'American wirehair'),
(2, 'Americano de pelo corto'),
(2, 'Asiático'),
(2, 'Australian mist'),
(2, 'Azul ruso'),
(2, 'Bengala'),
(2, 'Birmano'),
(2, 'Bombay'),
(2, 'Británico de pelo corto'),
(2, 'Burmilla'),
(2, 'Cornish rex'),
(2, 'Curl americano'),
(2, 'Devon Rex'),
(2, 'Don Sphynx'),
(2, 'Esfinge'),
(2, 'German rex'),
(2, 'Havana'),
(2, 'Korat'),
(2, 'Kurilian bobtail'),
(2, 'Manx'),
(2, 'Mau egipcio'),
(2, 'Munchkin'),
(2, 'Ocicat'),
(2, 'Ojos de diamante'),
(2, 'Oriental'),
(2, 'Peterbald'),
(2, 'Pixiebob'),
(2, 'Seychellois'),
(2, 'Siamés'),
(2, 'Siamés tradicional'),
(2, 'Singapura'),
(2, 'Snowshoe'),
(2, 'Sokoke'),
(2, 'Tonkinés');*/

/*INSERT INTO razas ( id_especie, nombre_raza)
VALUES
(1, 'Mestizo');*/

/*INSERT INTO razas ( id_especie, nombre_raza)
VALUES
(1, 'Affenpinscher'),
(1, 'Afgano'),
(1, 'Akita japonés'),
(1, 'American Staffordshire Terrier'),
(1, 'Australian Terrier'),
(1, 'Basenji'),
(1, 'Basset Azul de Gascuña'),
(1, 'Basset Grifón vandeano (pequeño)'),
(1, 'Basset Hound'),
(1, 'Basset leonado de Bretaña'),
(1, 'Beagle'),
(1, 'Beauceron'),
(1, 'Bedlington Terrier'),
(1, 'Bergamasco'),
(1, 'Bichón Boloñés'),
(1, 'Bichón frisé'),
(1, 'Bichón Matlés'),
(1, 'Bloodhound'),
(1, 'Bodeguero Andaluz'),
(1, 'Border collie'),
(1, 'Border terrier'),
(1, 'Boston Terrier'),
(1, 'Bóxer'),
(1, 'Boyero de Berna'),
(1, 'Boyero de Flandes'),
(1, 'Bracco italiano'),
(1, 'Braco alemán de pelo corto'),
(1, 'Braco alemán de pelo duro'),
(1, 'Braco de Weimar (de pelo corto y suave)'),
(1, 'Braco húngaro'),
(1, 'Braco húngaro de pelo duro'),
(1, 'Bretón'),
(1, 'Buhund noruego'),
(1, 'Bull Terrier miniatura'),
(1, 'Bulldog'),
(1, 'Bulldog francés'),
(1, 'Bullmastiff'),
(1, 'Cairn Terrier'),
(1, 'Caniche enano'),
(1, 'Caniche grande'),
(1, 'Caniche toy'),
(1, 'Carlino'),
(1, 'Cavalier King Charles Spaniel'),
(1, 'Chihuahua (de pelo largo)'),
(1, 'Chihuahua (de pelo suave)'),
(1, 'Chin japonés'),
(1, 'Chow Chow (de pelo suave)'),
(1, 'Clumber Spaniel'),
(1, 'Cobrador de Nueva Escocia'),
(1, 'Cockapoo'),
(1, 'Cocker spaniel'),
(1, 'Cocker Spaniel americano'),
(1, 'Collie barbudo'),
(1, 'Collie de pelo corto'),
(1, 'Corgi galés de Cardigan (de pelo medio/largo)'),
(1, 'Corgi galés de Pembroke'),
(1, 'Cotón de Tulear'),
(1, 'Crestado chino'),
(1, 'Crestado rodesiano (rhodesian ridgeback)'),
(1, 'Dálmata'),
(1, 'Dandie Dinmont Terrier'),
(1, 'Dóberman'),
(1, 'Dogo Argentino'),
(1, 'Dogo de Burdeos'),
(1, 'Field Spaniel'),
(1, 'Fox Terrier de pelo duro'),
(1, 'Fox Terrier de pelo liso'),
(1, 'Foxhound'),
(1, 'Galgo'),
(1, 'Galgo italiano'),
(1, 'Golden retriever'),
(1, 'Gran azul de Gascuña'),
(1, 'Grifón de Bruselas (pelaje corto y áspero)'),
(1, 'Grifón perro o Basset grifón vandeano (grande)'),
(1, 'Habanero'),
(1, 'Hamilton Stovare'),
(1, 'Hovawart'),
(1, 'Husky siberiano'),
(1, 'Keeshond'),
(1, 'Kerry blue Terrier'),
(1, 'King Charles Spaniel'),
(1, 'Komondor'),
(1, 'Kuvasz húngaro'),
(1, 'Labradoodle'),
(1, 'Labrador retriever'),
(1, 'Laekenois'),
(1, 'Lakeland Terrier'),
(1, 'Lancashire Heeler'),
(1, 'Lebrel escocés'),
(1, 'Lhasa Apso'),
(1, 'Lobero irlandés'),
(1, 'Lowchen (pequeño perro león)'),
(1, 'Malamute de Alaska'),
(1, 'Manchester Terrier'),
(1, 'Mastín Español'),
(1, 'Mastín inglés o mastiff'),
(1, 'Mastín napolitano'),
(1, 'Mastín tibetano'),
(1, 'Munsterlander (grande)'),
(1, 'Otterhound'),
(1, 'Pachón Navarro'),
(1, 'Papillón'),
(1, 'Parson jack russell terrier (de pelo corto/suave)'),
(1, 'Pastor Australiano'),
(1, 'Pastor belga Groenendael'),
(1, 'Pastor belga Tervueren'),
(1, 'Pastor de Anatolia'),
(1, 'Pastor de Brie o Briard'),
(1, 'Pastor de Los Pirineos'),
(1, 'Pastor de Maremma'),
(1, 'Pastor de Shetland (Shetland sheepdog)'),
(1, 'Pastor ganadero australiano'),
(1, 'Pastor Garafiano'),
(1, 'Pastor lapón de Suecia'),
(1, 'Pastor polaco de las llanuras'),
(1, 'Perdiguero de Burgos'),
(1, 'Perdiguero portugués'),
(1, 'Perro Bull terrier'),
(1, 'Perro Cane Corso o mastín italiano'),
(1, 'Perro de agua español'),
(1, 'Perro de agua irlandés'),
(1, 'Perro de agua portugués'),
(1, 'Perro de Canaán'),
(1, 'Perro de Groenlandia'),
(1, 'Perro de montaña de los Pirineos'),
(1, 'Perro de pastor Mallorquín'),
(1, 'Perro del faraón'),
(1, 'Perro Esquimal Americano'),
(1, 'Perro finlandés de Laponia'),
(1, 'Perro Leonés de Pastor'),
(1, 'Perro Lobo Checoslovaco'),
(1, 'Perro mini Pinscher'),
(1, 'Perro pastor blanco suizo'),
(1, 'Perro pastor catalán o gos datura'),
(1, 'Perro Pastor del Cáucaso'),
(1, 'Perro Pastor Vasco'),
(1, 'Perro pointer inglés'),
(1, 'Perro Serra da Estrela'),
(1, 'Pinscher alemán'),
(1, 'Pitbull terrier americano'),
(1, 'Podenco Canario'),
(1, 'Podenco ibicenco (de pelo corto y liso)'),
(1, 'Podenco Maneto'),
(1, 'Podenco portugués'),
(1, 'Pomerania'),
(1, 'Puli húngaro'),
(1, 'Ratonero Valenciano'),
(1, 'Raza de perros grandes: Borzoi'),
(1, 'Raza Gran Danés'),
(1, 'Raza pastor alemán'),
(1, 'Raza perro chow chow (de pelo duro)'),
(1, 'Retriever de Chesapeake'),
(1, 'Retriever de pelo liso'),
(1, 'Retriever de pelo rizado'),
(1, 'Rottweiler'),
(1, 'Rough Collie o Pastor Escocés'),
(1, 'Sabueso bávaro de montaña'),
(1, 'Sabueso Español'),
(1, 'Sabueso italiano (de pelo corto y suave)'),
(1, 'Saluki (galgo persa)'),
(1, 'Samoyedo'),
(1, 'San Bernardo (de pelo medio/largo)'),
(1, 'Schipperke'),
(1, 'Schnauzer estándar'),
(1, 'Schnauzer gigante'),
(1, 'Schnauzer miniatura'),
(1, 'Sealyham Terrier'),
(1, 'Setter escocés'),
(1, 'Setter inglés'),
(1, 'Setter irlandés'),
(1, 'Setter irlandés rojo y blanco'),
(1, 'Shar Pei'),
(1, 'Shiba Inu japonés'),
(1, 'Shih Tzu'),
(1, 'Silky Terrier australiano'),
(1, 'Skye Terrier'),
(1, 'Sloughi (galgo árabe)'),
(1, 'Soft Coated Wheaten Terrier'),
(1, 'Spaniel holandés'),
(1, 'Spaniel tibetano'),
(1, 'Spinone italiano'),
(1, 'Spitz alemán mediano'),
(1, 'Spitz alemán pequeño'),
(1, 'Spitz finlandés'),
(1, 'Spitz japonés'),
(1, 'Springer Spaniel galés'),
(1, 'Springer spaniel inglés'),
(1, 'Staffordshire bull terrier'),
(1, 'Sussex Spaniel'),
(1, 'Teckel (pelo largo)'),
(1, 'Teckel de pelo duro'),
(1, 'Teckel de pelo liso'),
(1, 'Teckel miniatura de pelo duro'),
(1, 'Teckel miniatura de pelo largo'),
(1, 'Teckel miniatura de pelo liso'),
(1, 'Terranova perro (Newfoundland)'),
(1, 'Terrier Checo'),
(1, 'Terrier de Airedale'),
(1, 'Terrier de Norfolk (Norfolk Terrier)'),
(1, 'Terrier de Norwich (Norwich terrier)'),
(1, 'Terrier escocés (scottish terrier)'),
(1, 'Terrier galés'),
(1, 'Terrier irlandés'),
(1, 'Terrier tibetano'),
(1, 'Toy Terrier inglés (negro y fuego)'),
(1, 'Vallhund sueco'),
(1, 'West Highland White Terrier'),
(1, 'Whippet'),
(1, 'Xoloitzcuintle (mediano)'),
(1, 'Yorkshire Terrier')
;*/

#INSERT INTO direccion ( nombre_lugar, direccion, ciudad, estado, pais) VALUES ('Casa','Av. Principal #123','La Paz','BCS','México');

#INSERT INTO duenos (curp, nombres, apellido_paterno, telefono, id_direccion)VALUES ('ABCD123456HDFRRN01','Juan','Perez','6121234567', 1);

#INSERT INTO animal (id_dueno, id_raza, nombre, peso, colores, sexo, esterilizado, carnet_de_vacunacion) VALUES ( 1, 1, 'Luna', 18.5, 'Blanco y negro', 'F', TRUE, TRUE);